// Persona presets shared by the PersonaPicker (Token Detail) and the onboarding
// wizard. PERSONA_CAP_DEFAULTS mirrors personas.py PERSONA_DEFINITIONS and is
// used to pre-fill cap values when applying a persona via PATCH so the matrix
// updates in one round-trip. If this drifts from the backend, the backend
// validates each value and the PATCH fails closed.
import type { Persona } from "./types";

export interface PersonaDef {
  key: Persona;
  labelKey: string;
  descriptionKey: string;
  // wizardOnly personas are shown only in the onboarding wizard's persona step,
  // not in the normal Token Detail persona picker.
  wizardOnly?: boolean;
}

export const PERSONAS: PersonaDef[] = [
  {
    key: "read_only",
    labelKey: "personas.read_only.label",
    descriptionKey: "personas.read_only.description",
  },
  {
    key: "voice_assistant",
    labelKey: "personas.voice_assistant.label",
    descriptionKey: "personas.voice_assistant.description",
  },
  {
    key: "dashboard_designer",
    labelKey: "personas.dashboard_designer.label",
    descriptionKey: "personas.dashboard_designer.description",
  },
  {
    key: "maintenance",
    labelKey: "personas.maintenance.label",
    descriptionKey: "personas.maintenance.description",
  },
  {
    key: "automation_builder",
    labelKey: "personas.automation_builder.label",
    descriptionKey: "personas.automation_builder.description",
  },
  {
    key: "power_user",
    labelKey: "personas.power_user.label",
    descriptionKey: "personas.power_user.description",
  },
  {
    key: "home_admin",
    labelKey: "personas.home_admin.label",
    descriptionKey: "personas.home_admin.description",
  },
  {
    key: "new_user",
    labelKey: "personas.new_user.label",
    descriptionKey: "personas.new_user.description",
  },
  {
    key: "esphome",
    labelKey: "personas.esphome.label",
    descriptionKey: "personas.esphome.description",
  },
  {
    key: "custom",
    labelKey: "personas.custom.label",
    descriptionKey: "personas.custom.description",
  },
];

export const PERSONA_CAP_DEFAULTS: Record<Persona, Record<string, string> | null> = {
  new_user: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "deny",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "deny",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "confirm",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  read_only: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "deny",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  voice_assistant: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "deny",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "confirm",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  dashboard_designer: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "deny",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "deny",
    cap_broadcast: "deny",
    cap_service_response: "deny",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "deny",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "allow",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "confirm",
    cap_backup: "deny",
    cap_filesystem: "confirm",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  maintenance: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "deny",
    cap_restart: "confirm",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "confirm",
    cap_radio_write: "confirm",
    cap_energy_write: "deny",
    cap_backup: "allow",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  automation_builder: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_blueprint_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "confirm",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  power_user: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_blueprint_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "allow",
    cap_integration_write: "confirm",
    cap_integration_reconfigure: "confirm",
    cap_lovelace_write: "confirm",
    cap_registry_write: "confirm",
    cap_radio_write: "confirm",
    cap_energy_write: "confirm",
    cap_backup: "confirm",
    cap_filesystem: "deny",
    cap_esphome_yaml: "deny",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "deny",
  },
  home_admin: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "allow",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "allow",
    cap_diagnostics: "allow",
    cap_broadcast: "allow",
    cap_service_response: "allow",
    cap_automation_write: "allow",
    cap_script_write: "allow",
    cap_blueprint_write: "allow",
    cap_scene_write: "allow",
    cap_helper_write: "allow",
    cap_physical_control: "confirm",
    cap_restart: "confirm",
    cap_integration_write: "confirm",
    cap_integration_reconfigure: "confirm",
    cap_lovelace_write: "confirm",
    cap_registry_write: "confirm",
    cap_radio_write: "confirm",
    cap_energy_write: "confirm",
    cap_backup: "confirm",
    cap_filesystem: "confirm",
    cap_esphome_yaml: "confirm",
    cap_esphome_flash: "deny",
    cap_yaml_edit: "confirm",
  },
  esphome: {
    cap_config_read: "allow",
    cap_camera_read: "deny",
    cap_template_render: "deny",
    cap_log_read: "allow",
    cap_log_control: "deny",
    cap_search: "allow",
    cap_registry_read: "allow",
    cap_traces: "deny",
    cap_diagnostics: "allow",
    cap_broadcast: "deny",
    cap_service_response: "allow",
    cap_automation_write: "deny",
    cap_script_write: "deny",
    cap_blueprint_write: "deny",
    cap_scene_write: "deny",
    cap_helper_write: "deny",
    cap_physical_control: "deny",
    cap_restart: "deny",
    cap_integration_write: "deny",
    cap_integration_reconfigure: "deny",
    cap_lovelace_write: "deny",
    cap_registry_write: "deny",
    cap_radio_write: "deny",
    cap_energy_write: "deny",
    cap_backup: "deny",
    cap_filesystem: "deny",
    cap_esphome_yaml: "confirm",
    cap_esphome_flash: "confirm",
    cap_yaml_edit: "deny",
  },
  custom: null,
};
