"""Block a git commit that changes source without touching any documentation.

A pre-commit hook. Reads the hook JSON on stdin; if the command is a git
commit and the STAGED diff touches source files while staging no documentation
file, it denies the commit with instructions. The
escape hatch is deliberate and auditable: a commit message containing
"[no-docs]" (with a reason) passes, so a genuinely doc-free change is a
conscious, recorded decision instead of a silent omission.

Source = custom_components/phoenix_mcp/ Python and frontend_src/. Docs = docs/,
README.md, the project's own specification and instruction files, or the
translation catalogs. tests/, scripts/, and build output count as neither: they
never trigger the guard and never satisfy it.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys

# `git commit`, allowing the global options git accepts before the subcommand
# (-C <path>, -c k=v, --git-dir=..., -P, ...). A plain substring test missed
# `git -C . commit` entirely, which is a silent bypass rather than a refusal.
# Anchored to the start of a command (line start, or after a shell separator)
# so `git add . && git commit` is caught while `echo git commit ...` is not.
_GIT_COMMIT = re.compile(
    r"(?:^|[;&|]|\n)\s*git\b(?:\s+(?:-[-\w]+(?:=\S+)?|-[cC]\s+\S+))*\s+commit\b"
)
# The marker must carry a reason: "[no-docs]" alone records nothing, and the
# whole point of the escape hatch is that skipping docs is a stated decision.
# The reason has to start with an actual word, so a bare marker followed by the
# closing quote of -m does not read as one.
_NO_DOCS = re.compile(r"\[no-docs\]\s+[A-Za-z0-9]")


def _classify(path: str) -> str:
    if path.startswith("docs/") or path in ("README.md", "SPEC.md", "CLAUDE.md"):
        return "docs"
    if path == "custom_components/phoenix_mcp/CLAUDE.md":
        return "docs"
    if path.startswith((
        "custom_components/phoenix_mcp/translations/",
        "custom_components/phoenix_mcp/catalogs/",
    )):
        return "docs"
    if path.startswith("custom_components/phoenix_mcp/frontend/"):
        return "other"  # build output
    if path.startswith("custom_components/phoenix_mcp/mesa_core/"):
        return "other"  # vendored, regenerated by sync script
    if path.startswith(("tests/", "scripts/", "frontend_src/__tests__/")):
        return "other"
    if path.startswith(("custom_components/phoenix_mcp/", "frontend_src/")):
        return "source"
    return "other"


def main() -> None:
    try:
        payload = json.load(sys.stdin)
    except Exception:
        return  # malformed input: never block on our own bug
    command = str((payload.get("tool_input") or {}).get("command") or "")
    if not _GIT_COMMIT.search(command):
        return
    if _NO_DOCS.search(command):
        return
    try:
        staged = subprocess.run(
            ["git", "diff", "--cached", "--name-only"],
            capture_output=True, text=True, timeout=15, check=True,
        ).stdout.splitlines()
    except Exception:
        return  # can't inspect the diff: never block on our own failure
    kinds = {_classify(p) for p in staged if p}
    if "source" in kinds and "docs" not in kinds:
        srcs = [p for p in staged if _classify(p) == "source"]
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": (
                    "Docs guard: this commit stages source changes ("
                    + ", ".join(srcs[:5])
                    + (" and more" if len(srcs) > 5 else "")
                    + ") but no documentation file (docs/, README.md, SPEC.md,"
                    " CLAUDE.md, translations). Per the strict docs rule, update"
                    " the docs in the SAME commit and run the /docs-verify pass,"
                    " or, if this change genuinely needs no docs, add"
                    " '[no-docs] <reason>' to the commit message."
                ),
            }
        }))


if __name__ == "__main__":
    main()
